### PR TITLE
UPLC Shrinking

### PR DESCRIPTION
**Pull request by Geometer1729**
This is the UPLC shrinking module I've been working on.

### CODE REVIEW

**Comment by L-as** [comment]
Do you know what the asymptotic time and space complexities of the algorithms you're using are?

**Comment by Geometer1729** [comment]
I think the worst case is O(n^3). It may be possible to prove a faster complexity with fairly weak assumptions about the input.

**Comment by L-as** [comment]
Since Plutus scripts are inherently bounded, we don't have to care about it too much, but I'd prefer that you test this with a script that is ~15 KB each to make sure that it terminates on a standard machine.

**Comment by L-as** [comment]
Well TBF if the user can choose not to shrink, it's not a huge worry.

**Pull request closed without merging**
